SELECT EMAIL, NOMBRE, DOCUMENTO, DIRECCION
FROM INFO_PRODUCTO_SUCURSAL IPS, (
SELECT *
FROM CLIENTES C, VENTAS V
WHERE C.DOCUMENTO = V.DOCUMENTOCLIENTE) B
WHERE IPS.IDVENTA = B.ID
--Sentencia de las restrincciones--
GROUP BY B.DOCUMENTO, B.NOMBRE, B.DIRECCION, B.EMAIL
ORDER BY DOCUMENTO;