SELECT * FROM (select count(*) Sucursal from sucursal),
(select count(*) Proveedor from proVEEDOR),
(select count(*) Categoria from categoria),
(select count(*) TipoProducto from tipo_producto),
(select count(*) Producto from producto),
(select count(*) Prod_Prov from producto_proveedor),
(select count(*) Prod_Sucursal from producto_sucursal),
(select count(*) Prod_redimible from producto_redimible),
(select count(*) Promocion from promocion),
(select count(*) Orden_pedido from Orden_pedido),
(select count(*) Info_Prod_provee from INFO_PRODUCTO_PROVEEDOR),
(select count(*) Almacenamiento from almacenamiento),
(select count(*) Cliente from clientes),
(select count(*) ventas from ventas),
(select count(*) Info_prod_sucursal from info_producto_sucursal),
(select count(*) carrito from carrito),
(select count(*) info_Prod_Carrito from info_producto_carrito);
